repository:
  tag: v{{ .Values.BUILD_NUMBER }} # This will be replaced with the actual build number during deployment
  assets:
    image: devopseasylearning/s5wesley-rock-music-band
Values:
  repository:
    assets:
      image: devopseasylearning/s5wesley-rock-music-band
    tag: "6"
